### ISSUE TITLE
Clarification on Java 8  support

### ISSUE THREAD

**Issue by rshanmugam1** [IBM/java-iceberg-toolkit#1]
Thanks for creating this project. 

Document says java version 13 and above. but pom.xml compiled against java 8.  https://github.com/IBM/java-iceberg-toolkit/blob/b8be05efc48a208eafce1146cd78e8b460b28988/tools/java-iceberg-cli/pom.xml#L10 

does this work java 8?. if yes, better to update document.

**Comment by s-akhtar-baig** [comment]
@rshanmugam1, thank you for raising the issue.

Yes, the code can be packaged with java 8, however, java 13 and above is required for running the unit tests. I have created a pull request that lists the dependencies separately in the readme file.

**Comment by rshanmugam1** [comment]
👍
